# Generated by Django 4.0.1 on 2022-01-21 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('significance_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checks.locations')),
            ],
        ),
        migrations.CreateModel(
            name='ControlEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checks.objects')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checks.controlevent')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checks.grades')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checks.questions')),
            ],
            options={
                'unique_together': {('control_event', 'question', 'grade')},
            },
        ),
    ]
