# Generated by Django 4.1 on 2023-10-09 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePositionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checks.employeeposition')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checks.question')),
            ],
        ),
    ]
