# Generated by Django 4.0.1 on 2022-01-22 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0002_rename_grades_grade_rename_locations_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlevent',
            name='object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='checks.object'),
        ),
    ]
