# Generated by Django 4.1 on 2023-10-11 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0003_question_relational_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='relational_question',
        ),
        migrations.AddField(
            model_name='question',
            name='parent_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_question', to='checks.question'),
        ),
    ]
