# Generated by Django 4.0.1 on 2022-02-01 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0003_alter_controlevent_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Наименование района'),
        ),
        migrations.AlterField(
            model_name='object',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='checks.location'),
        ),
    ]
