# Generated by Django 4.0.1 on 2022-02-08 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0004_alter_location_name_alter_object_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlevent',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checks.object'),
        ),
    ]
