# Generated by Django 4.1 on 2023-10-12 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0004_remove_question_relational_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='parent_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_question', to='checks.question'),
        ),
    ]
