# Generated by Django 4.1 on 2023-10-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0005_alter_question_parent_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sort_id',
            field=models.IntegerField(null=True),
        ),
    ]
